@host = http://localhost:8080
@basePath = {{host}}/employees

### 1. Создать сотрудника
POST {{basePath}}
Content-Type: application/json

{
  "name": "Иван",
  "surname": "Петров",
  "email": "ivan.petrov@example.com",
  "password": "securePass123",
  "role"  : "MANAGER"
}

### 2. Получить сотрудника по ID
GET {{basePath}}/1

### 3. Получить всех сотрудников
GET {{basePath}}

### 4. Обновить сотрудника
PUT {{basePath}}/1
Content-Type: application/json

{
  "name": "Иван",
  "surname": "Петровский",
  "email": "ivan.petrovsky@example.com",
  "password": "newSecurePass456",
  "role": "MANAGER"
}

### 5. Удалить сотрудника (DELETE)
DELETE {{basePath}}/1