@host = http://localhost:8080
@basePath = {{host}}/employees

### Создать сотруднико 1
POST {{basePath}}
Content-Type: application/json

{
  "name": "Иван",
  "surname": "Петров",
  "email": "ivan.petrov@example.com",
  "password": "securePass123",
  "role"  : "MANAGER"
}

### Создать сотруднико 2
POST {{basePath}}
Content-Type: application/json

{
  "name": "Владимир",
  "surname": "Иванов",
  "email": "vladimir@example.com",
  "password": "securePa23",
  "role"  : "ADMIN"
}

### Создать сотруднико 3 (Не успех)
POST {{basePath}}
Content-Type: application/json

{
  "name": "Тест",
  "surname": "Тест",
  "email": "vladimir@example.com",
  "password": "securePa23",
  "role"  : "ADMIN"
}


### Получить сотрудника по ID
GET {{basePath}}/1

### Получить сотрудника по ID (Не успех)
GET {{basePath}}/100500

### Получить всех сотрудников
GET {{basePath}}

### Обновить сотрудника
PUT {{basePath}}/1
Content-Type: application/json

{
  "name": "Иван",
  "surname": "Петровский",
  "email": "petrovsky@example.com",
  "password": "newSecurePass456",
  "role": "MANAGER"
}

### Обновить сотрудника (не успех)
PUT {{basePath}}/1
Content-Type: application/json

{
  "name": "Иван",
  "surname": "Петровский1",
  "email": "vladimir@example.com",
  "password": "newSecurePass456",
  "role": "MANAGER"
}

### Удалить сотрудника (DELETE)
DELETE {{basePath}}/1

### Удалить сотрудника (Не успех)
DELETE {{basePath}}/1