### Создать сотрудника (Ошибка 500)
POST {{basePath}}
Content-Type: application/json

{
  "name": "Иван",
  "surname": "",
  "email": "petrov",
  "password": "securePass123",
  "role": "ERR"
}

### Создать сотрудника (ошибка валидации 400)
POST {{basePath}}
Content-Type: application/json

{
  "name": "Иван",
  "surname": "",
  "email": "petrov",
  "password": "securePass123",
  "role": "MANAGER"
}
### Создать сотрудника 1
POST {{basePath}}
Content-Type: application/json

{
  "name": "Иван",
  "surname": "Петров",
  "email": "ivan.petrov@example.com",
  "password": "securePass123",
  "role": "MANAGER"
}

### Создать сотрудника 2
POST {{basePath}}
Content-Type: application/json

{
  "name": "Владимир",
  "surname": "Иванов",
  "email": "vladimir@example.com",
  "password": "securePa23",
  "role": "ADMIN"
}

### Создать сотрудника 3
POST {{basePath}}
Content-Type: application/json

{
  "name": "Влад",
  "surname": "Рыбин",
  "email": "vlad@example.com",
  "password": "secePa23",
  "role": "MANAGER"
}


### Создать сотрудника 3 (Не успех)
POST {{basePath}}
Content-Type: application/json

{
  "name": "Тест",
  "surname": "Тест",
  "email": "vladimir@example.com",
  "password": "securePa23",
  "role": "ADMIN"
}

### Получить сотрудника по ID
GET {{basePath}}/1

### Получить сотрудника по ID (Не успех)
GET {{basePath}}/100500


### Получить сотрудника фильтр email
GET {{basePath}}?email=ivan.petrov@example.com

### Получить сотрудника фильтры
GET {{basePath}}?name=Иван&surname=Петров&email=ivan.petrov@example.com&page=0&size=5&sort=id,asc

### Получить всех сотрудников
GET {{basePath}}

### Получить всех сотрудников пагинация 1
GET {{basePath}}/?page=0&size=2&sort=id

### Получить всех сотрудников пагинация 2
GET {{basePath}}/?page=1&size=2&sort=id,desc

### Получить всех сотрудников пагинация 3
GET {{basePath}}/?page=2&size=1

### Обновить сотрудника
PUT {{basePath}}/1
Content-Type: application/json

{
  "name": "Иван",
  "surname": "Петровский",
  "email": "petrovsky@example.com",
  "password": "newSecurePass456",
  "role": "MANAGER"
}

### Обновить сотрудника (не успех)
PUT {{basePath}}/1
Content-Type: application/json

{
  "name": "Иван",
  "surname": "Петровский1",
  "email": "vladimir@example.com",
  "password": "newSecurePass456",
  "role": "MANAGER"
}

### Удалить сотрудника
DELETE {{basePath}}/1

### Удалить сотрудника (Не успех)
DELETE {{basePath}}/1