spring:
  application:
    name: employee-manager

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employee_db
    username: root
    password: root

  sql:
    init:
      mode: always

  jpa:
    #show-sql: true
    hibernate:
      #ddl-auto: none
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        #dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.SQL: DEBUG