spring:
  application:
    name: employee-manager
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 20

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha