DROP TABLE IF EXISTS employees;

CREATE TABLE IF NOT EXISTS employees
(
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    surname     VARCHAR(100) NOT NULL,
    email       VARCHAR(100) NOT NULL,
    password    VARCHAR(64)  NOT NULL,
    role        VARCHAR(30)  NOT NULL,
    CONSTRAINT uc_user_email UNIQUE (email)
);
