DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS customers;

CREATE TABLE IF NOT EXISTS employees
(
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    surname     VARCHAR(100) NOT NULL,
    email       VARCHAR(100) NOT NULL,
    phone       VARCHAR(30),
    password    VARCHAR(64)  NOT NULL,
    role        VARCHAR(30)  NOT NULL,
    CONSTRAINT uc_employee_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS customers
(
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    surname     VARCHAR(100) NOT NULL,
    email       VARCHAR(100) NOT NULL,
    phone       VARCHAR(30)  NOT NULL,
    CONSTRAINT uc_customer_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS orders
(
    order_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    status      VARCHAR(30),
    customer_id BIGINT,
    CONSTRAINT fk_orders_customer_id FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
        ON DELETE SET NULL
);
CREATE INDEX idx_orders_customer_id ON orders (customer_id);

-- ============================================
-- ТЕСТОВЫЕ ДАННЫЕ
-- ============================================

INSERT INTO employees (name, surname, email, phone, password, role)
VALUES ('Александр', 'Иванов', 'alexander.ivanov@company.ru', '+79001112233', 'admin123', 'ADMIN'),
       ('Мария', 'Петрова', 'maria.petrova@company.ru', '+79002223344', 'manager123', 'MANAGER'),
       ('Дмитрий', 'Сидоров', 'dmitry.sidorov@company.ru', '+79003334455', 'user123', 'MANAGER'),
       ('Елена', 'Козлова', 'elena.kozlova@company.ru', '+79004445566', 'user456', 'MANAGER');

INSERT INTO customers (name, surname, email, phone)
VALUES ('Иван', 'Смирнов', 'ivan.smirnov@mail.ru', '+79111234567'),
       ('Анна', 'Кузнецова', 'anna.kuznetsova@gmail.com', '+79122345678'),
       ('Пётр', 'Попов', 'petr.popov@yandex.ru', '+79133456789'),
       ('Светлана', 'Васильева', 'svetlana.vasileva@mail.ru', '+79144567890'),
       ('Михаил', 'Зайцев', 'mikhail.zaytsev@gmail.com', '+79155678901');

INSERT INTO orders (created_at, status, customer_id)
VALUES
-- Иван Смирнов
('2026-01-15 10:30:00+03', 'NEW', 1),
('2026-02-20 14:45:00+03', 'COMPLETED', 1),

-- Анна Кузнецова
('2026-03-10 09:15:00+03', 'PROCESSING', 2),

-- Пётр Попов
('2026-04-05 16:20:00+03', 'NEW', 3),
('2026-05-18 10:00:00+03', 'CANCELLED', 3),

-- Светлана Васильева
('2026-06-01 14:15:00+03', 'PROCESSING', 4);

-- Михаил Зайцев 0 заказов
