CREATE TABLE IF NOT EXISTS employees
(
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    surname     VARCHAR(100) NOT NULL,
    email       VARCHAR(100) NOT NULL,
    phone       VARCHAR(30),
    password    VARCHAR(64)  NOT NULL,
    role        VARCHAR(30)  NOT NULL,
    CONSTRAINT uc_employee_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS customers
(
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    surname     VARCHAR(100) NOT NULL,
    email       VARCHAR(100) NOT NULL,
    phone       VARCHAR(30)  NOT NULL,
    CONSTRAINT uc_customer_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS orders
(
    order_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    status      VARCHAR(30),
    customer_id BIGINT,
    CONSTRAINT fk_orders_customer_id FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
        ON DELETE SET NULL
);
CREATE INDEX idx_orders_customer_id ON orders (customer_id);
