CREATE TABLE IF NOT EXISTS products
(
    product_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)   NOT NULL,
    description VARCHAR(511),
    price       NUMERIC(12, 2) NOT NULL,
    CONSTRAINT uc_product_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS order_items
(
    --Так проще,  не нужен @EmbeddedId и OrderItemId
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT NOT NULL,
    product_id    BIGINT NOT NULL,
    quantity      INT    NOT NULL,

    --CONSTRAINT pk_order_items PRIMARY KEY (order_id, product_id),
    CONSTRAINT uc_order_product UNIQUE (order_id, product_id),
    CONSTRAINT fk_order_items_order_id FOREIGN KEY (order_id) REFERENCES orders (order_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product_id FOREIGN KEY (product_id) REFERENCES products (product_id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_order_items_order_id ON order_items (order_id);
CREATE INDEX idx_order_items_product_id ON order_items (product_id);
